[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
workouts = "4tRQBjKLrcbkX4gqd3xbVmacn1QgSZX59QczBLv32bPG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
